### ISSUE TITLE
Notebook Readability Issue

### ISSUE THREAD

**Issue by fazaghifari** [Ultios/StraPy#12]
Please do not print all the matrices in your notebook. Esp, in cell no. 33. 
![image](https://user-images.githubusercontent.com/26693799/198464065-155752fd-83f3-4f5c-b75c-d43cdbb21090.png)

It's very inconvenient for people to check your work.

**Comment by Ultios** [comment]
Thanks for the suggestion! Hopefully it will  be more readable now.
